
# Notebook 41 (Claude) — Closure with a Decision-Sensitivity Statement

**Zero simulations.**

A terminal status nobody has stress-tested is a status whose dependence on a single metric
is invisible. Phase 2 is the artifact the Cursor closure lacks: the same evidence read
several defensible ways, and where each reading lands.

| | |
|---|---|
| 0 | immutables + both upstream handoffs |
| 1 | intervention justification, established by search |
| 2 | **decision sensitivity** |
| 3 | terminal status |
| 4 | dissertation paragraph, clause by clause |
| 5 | final audits |

In [1]:
import json, sys
from pathlib import Path

import numpy as np
import pandas as pd

SRC = Path.cwd().resolve().parents[0] / "src"
if not SRC.is_dir():
    SRC = Path.cwd().resolve().parents[1] / "S4_sbi" / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from sleep_sbi import figure10_closure_claude_common as common
from sleep_sbi.figure10_protocol import PROJECT_ROOT

pd.set_option("display.width", 160)
pd.set_option("display.max_columns", 40)


def show(payload, keys=None):
    """Print a JSON-ish payload compactly, optionally restricted to some keys."""
    if keys is not None:
        payload = {k: payload[k] for k in keys if k in payload}
    print(json.dumps(payload, indent=2, ensure_ascii=False, default=str)[:4000])


print("python  :", sys.version.split()[0])
print("env     :", Path(sys.executable).parent.name)
print("src     :", SRC)

python  : 3.10.20
env     : neurolib
src     : D:\Year3_Mao_Projects\sleep_loop\S4_sbi\src

In [2]:

from sleep_sbi import figure10_notebook41_claude as nb41

paths = common.claude_dirs(41)
common.assert_immutables()
handoff39, nb40_claude = nb41.load_handoffs()
print("39 -> 40 handoff:", handoff39["claude40_handoff_status"])
print("40 -> 41 handoff:", nb40_claude["claude41_handoff_status"])
print("7D direction    :", nb40_claude["seven_d"]["descriptive_evidence_direction"])
print("8D direction    :", nb40_claude["eight_d"]["descriptive_evidence_direction"])

39 -> 40 handoff: CONTINUE
40 -> 41 handoff: CONTINUE
7D direction    : INDISTINGUISHABLE
8D direction    : INDISTINGUISHABLE


## Phase 1 — Intervention justification

`CONTROL_NOT_JUSTIFIED` is the right call and the Cursor closure reached it. What it did
not do is *demonstrate* it — the status was frozen by assertion before any artifact was
consulted. Here each of the four elements a preregistered intervention needs is searched
for, by name, across every lock and preregistration in the project.

In [3]:

intervention = nb41.phase1_intervention(paths)
display(pd.read_csv(paths["csv"] / "intervention_elements.csv"))
print("artifacts searched:")
for artifact in intervention["artifacts_searched"]:
    print("   ", artifact)
print("missing:", intervention["missing_artifacts"] or "(none)")
print()
print(intervention["argument"])
print()
print("STATUS:", intervention["intervention_status"],
      "| simulations:", intervention["intervention_simulations_run"])

    element  present  n_hits                                      searched_keys
0  variable    False       0  intervention_variable;stim_variable;manipulate...
1  baseline    False       0             intervention_baseline;control_arm;sham
2    levels    False       0         intervention_levels;dose_levels;two_levels
3     seeds    False       0  intervention_seed;intervention_seeds;control_seed

artifacts searched:
    S4_sbi/results/figure10_8d_7d/preregistration/FIGURE10_8D_7D_PREREGISTRATION.md
    S4_sbi/configs/figure10_8d_7d_preregistered_v1.json
    S4_sbi/configs/notebook_39_41_closure/scientific_protocol_lock.json
    S4_sbi/configs/notebook_39_41_closure/execution_manifest.json
    S4_sbi/results/figure10_8d_7d/artifacts/notebook_38/json/protocol_lock.json
    S4_sbi/results/figure10_8d_7d/artifacts/notebook_38_claude/json/protocol_lock.json
missing: (none)

A preregistered intervention needs a manipulated variable, a baseline arm, at least two levels, and frozen seeds. None of the four appears under any of its accepted names in any of the 6 locks and preregistrations that govern this work. The status is therefore a finding about the record, not a policy choice.

STATUS: CONTROL_NOT_JUSTIFIED | simulations: 0


## Phase 2 — Decision sensitivity

Five readings of the same evidence. One of them is the shipped closure; the other four are
the readings that survive the Notebook 39 admissibility gate.

In [4]:

sensitivity = nb41.phase2_decision_sensitivity(paths, nb40_claude=nb40_claude,
                                               handoff39=handoff39)
display(pd.read_csv(paths["csv"] / "decision_sensitivity.csv"))

                               reading             families_counted       direction_7d                        terminal_status  admissible
0                    as_shipped_cursor  so_waveform;spindle_density              MIXED      HELDOUT_DESCRIPTIVE_EVIDENCE_ONLY       False
1   excluded_degenerate_point_estimate                  so_waveform        UNFAVORABLE  RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY        True
2  excluded_degenerate_sign_test_vs_v7                  so_waveform  INDISTINGUISHABLE  RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY        True
3  excluded_degenerate_sign_test_vs_v3                  so_waveform        UNFAVORABLE  RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY        True
4              no_admissible_direction                       (none)    UNINTERPRETABLE  RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY        True

In [5]:

for reading in sensitivity["readings"]:
    mark = "admissible" if reading["admissible"] else "INADMISSIBLE"
    print("─" * 100)
    print(f"{reading['reading']}  [{mark}]")
    print("   families :", ", ".join(reading["families_counted"]) or "(none)")
    print("   7D       :", reading["direction_7d"], "->", reading["terminal_status"])
    print("   why      :", reading["why"])

────────────────────────────────────────────────────────────────────────────────────────────────────
as_shipped_cursor  [INADMISSIBLE]
   families : so_waveform, spindle_density
   7D       : MIXED -> HELDOUT_DESCRIPTIVE_EVIDENCE_ONLY
   why      : Counts a family whose rule admits every density the model can produce; its FAVORABLE is what turns UNFAVORABLE into MIXED.
────────────────────────────────────────────────────────────────────────────────────────────────────
excluded_degenerate_point_estimate  [admissible]
   families : so_waveform
   7D       : UNFAVORABLE -> RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY
   why      : The Cursor rule itself, applied only to the family that can fail.
────────────────────────────────────────────────────────────────────────────────────────────────────
excluded_degenerate_sign_test_vs_v7  [admissible]
   families : so_waveform
   7D       : INDISTINGUISHABLE -> RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY
   why      : Two-sided sign test at alpha=0.05 against the frozen V7 baseline.
────────────────────────────────────────────────────────────────────────────────────────────────────
excluded_degenerate_sign_test_vs_v3  [admissible]
   families : so_waveform
   7D       : UNFAVORABLE -> RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY
   why      : Same test against V3, which the frozen protocol simulated under an identical protocol and then never read.
────────────────────────────────────────────────────────────────────────────────────────────────────
no_admissible_direction  [admissible]
   families : (none)
   7D       : UNINTERPRETABLE -> RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY
   why      : The most conservative reading: no family supplies a direction at all.

In [6]:

print("admissible terminal statuses:", sensitivity["admissible_terminal_statuses"])
print("invariant across them       :",
      sensitivity["terminal_status_invariant_across_admissible_readings"])
print("shipped status              :", sensitivity["shipped_status"])
print("shipped is the only outlier :", sensitivity["shipped_status_is_the_only_outlier"])
print()
alpha = sensitivity["alpha_independence"]
print(alpha["claim"])
print(alpha["reason"])
print("   candidates beating V7        : %d/%d" % (alpha["n_better_than_v7_observed"],
                                                   alpha["n_candidates"]))
print("   needed for significant FAV   : %d" % alpha["n_better_required_for_significant_favorable"])
print("   shortfall                    : %d" % alpha["shortfall"])
print()
print(sensitivity["single_metric_dependence"])

admissible terminal statuses: ['RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY']
invariant across them       : True
shipped status              : HELDOUT_DESCRIPTIVE_EVIDENCE_ONLY
shipped is the only outlier : True

No choice of alpha produces the shipped status on the admissible evidence.
Both possible sign-test outcomes against V7 -- significant-unfavorable and not-significant -- route to RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY. The only route to HELDOUT_DESCRIPTIVE_EVIDENCE_ONLY is a significant FAVORABLE.
   candidates beating V7        : 4/16
   needed for significant FAV   : 13
   shortfall                    : 9

One metric family with no discriminative power is the entire difference between the shipped status and every admissible reading of the same data.


## Phase 3 — Terminal status

The frozen 7D-only mapping, applied to the admissible evidence. 8D contributes
`sensitivity_concordance` and nothing else.

In [7]:

terminal = nb41.phase3_terminal(paths, nb40_claude=nb40_claude, handoff39=handoff39,
                                sensitivity=sensitivity, intervention=intervention)
show(terminal, ["global_uncertainty_status", "predictive_twin_status",
                "descriptive_evidence_direction_7d", "descriptive_evidence_direction_8d",
                "sensitivity_concordance", "sensitivity_concordance_is_deciding",
                "intervention_status", "final_part_ii_status", "decided_by",
                "invariant_across_admissible_readings", "admissible_families",
                "excluded_families", "failure_reasons"])

{
  "global_uncertainty_status": "NO_GO",
  "predictive_twin_status": "PREDICTIVE_UNQUALIFIED",
  "descriptive_evidence_direction_7d": "INDISTINGUISHABLE",
  "descriptive_evidence_direction_8d": "INDISTINGUISHABLE",
  "sensitivity_concordance": "CONCORDANT",
  "sensitivity_concordance_is_deciding": false,
  "intervention_status": "CONTROL_NOT_JUSTIFIED",
  "final_part_ii_status": "RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY",
  "decided_by": "7d_primary_only",
  "invariant_across_admissible_readings": true,
  "admissible_families": [
    "so_waveform"
  ],
  "excluded_families": [
    "spindle_density"
  ],
  "failure_reasons": [
    "seven_d_global_dev_fail",
    "empty_confirmatory_predictive_pass_set",
    "control_not_justified_no_preregistered_intervention",
    "sole_admissible_physiology_family_indistinguishable_from_baseline"
  ]
}


## Phase 4 — The dissertation paragraph

Every clause traced to the artifact that supports it, and the shipped sentence retracted
with its counter-evidence attached.

In [8]:

paragraph = nb41.phase4_paragraph(paths, terminal=terminal, nb40_claude=nb40_claude,
                                  sensitivity=sensitivity)
for i, clause in enumerate(paragraph["clauses"], start=1):
    print("─" * 100)
    print(f"[{i}] {clause['clause']}")
    print(f"     evidence: {clause['evidence']}")

────────────────────────────────────────────────────────────────────────────────────────────────────
[1] Global posterior qualification failed on both tracks and the failure was not repaired downstream.
     evidence: notebook_38/json/development_decision.json
────────────────────────────────────────────────────────────────────────────────────────────────────
[2] Of the two objective-disjoint physiology families, only slow-oscillation waveform morphology has a decision rule capable of returning an unfavorable answer within the range this model can produce; the spindle-density rule admits every attainable density and was excluded before its results were read.
     evidence: notebook_39_claude/json/metric_power_audit.json
────────────────────────────────────────────────────────────────────────────────────────────────────
[3] On that single admissible family the posterior candidates could not be distinguished from the frozen V7 point estimate on the primary track (4/16 candidates better, sign-test p = 0.077) or on the sensitivity track (p = 1.000), and were significantly worse than the older V3 estimate on the primary track (2/16, p = 0.0042).
     evidence: notebook_40_claude/json/direction_with_uncertainty.json
────────────────────────────────────────────────────────────────────────────────────────────────────
[4] Repeated simulation confirms the spread across candidates is a property of the parameter draw rather than simulator noise (93% of the variance on the primary track), so the width of that spread is itself a posterior finding.
     evidence: notebook_40_claude/json/variance_decomposition.json
────────────────────────────────────────────────────────────────────────────────────────────────────
[5] All 34 simulated arms -- every posterior candidate and both differential-evolution baselines -- produced no detector-visible sigma events, which is a limitation of the thalamo-cortical configuration rather than a comparison among arms.
     evidence: notebook_40_claude/json/nondiscriminative_family_report.json
────────────────────────────────────────────────────────────────────────────────────────────────────
[6] No preregistered intervention exists in the record, so no control experiment could be launched, and Part II closes as a reliability diagnostic framework rather than as validated posterior inference.
     evidence: notebook_41_claude/json/intervention_justification.json

In [9]:

print("PARAGRAPH\n")
print(paragraph["dissertation_paragraph"])
print()
print("=" * 100)
print("RETRACTED\n")
print(paragraph["retraction"]["retracted_sentence"])
print()
print(paragraph["retraction"]["reason"])

PARAGRAPH

Global posterior qualification failed on both tracks and the failure was not repaired downstream. Of the two objective-disjoint physiology families, only slow-oscillation waveform morphology has a decision rule capable of returning an unfavorable answer within the range this model can produce; the spindle-density rule admits every attainable density and was excluded before its results were read. On that single admissible family the posterior candidates could not be distinguished from the frozen V7 point estimate on the primary track (4/16 candidates better, sign-test p = 0.077) or on the sensitivity track (p = 1.000), and were significantly worse than the older V3 estimate on the primary track (2/16, p = 0.0042). Repeated simulation confirms the spread across candidates is a property of the parameter draw rather than simulator noise (93% of the variance on the primary track), so the width of that spread is itself a posterior finding. All 34 simulated arms -- every posterior candidate and both differential-evolution baselines -- produced no detector-visible sigma events, which is a limitation of the thalamo-cortical configuration rather than a comparison among arms. No preregistered intervention exists in the record, so no control experiment could be launched, and Part II closes as a reliability diagnostic framework rather than as validated posterior inference.

====================================================================================================
RETRACTED

The candidate simulations retained limited held-out physiological consistency relative to a frozen DE baseline on objective-disjoint descriptive metrics, but neither calibrated posterior uncertainty nor reliable intervention prediction was established.

The clause 'retained limited held-out physiological consistency relative to a frozen DE baseline' rests on the spindle-density FAVORABLE label. That label is a tie between two arms that both produced zero events, under a rule that admits every density the model can generate. On the one family with discriminative power the candidates are indistinguishable from V7 on both tracks and significantly worse than V3 on the primary track.


## Phase 5 — Final audits

In [10]:

audits = nb41.phase5_final_audits(paths)
show(audits, ["sealed", "no_notebook_42", "write_scope", "environment",
              "locks_read_not_written", "integrity_status"])
assert audits["integrity_status"] == "INTEGRITY_OK"
print("\nartifacts hashed:", len(audits["artifact_hashes"]))

{
  "sealed": {
    "directory": "S4_sbi/results/figure10_8d_7d/artifacts/notebook_38/sealed",
    "entries": [
      "sealed_state_registry.json"
    ],
    "case_arrays_present": [],
    "opened": false,
    "ok": true
  },
  "no_notebook_42": {
    "matches": [],
    "ok": true
  },
  "write_scope": {
    "allowed_roots": [
      "S4_sbi/results/figure10_8d_7d/artifacts/notebook_39_claude",
      "S4_sbi/results/figure10_8d_7d/artifacts/notebook_40_claude",
      "S4_sbi/results/figure10_8d_7d/artifacts/notebook_41_claude"
    ],
    "n_files_written": 47,
    "ok": true
  },
  "environment": {
    "python": "3.10.20",
    "executable": "C:\\Users\\YUS190\\AppData\\Local\\anaconda3\\envs\\neurolib\\python.exe",
    "platform": "Windows-10-10.0.19045-SP0",
    "numpy": "2.2.6",
    "conda_env_expected": "neurolib",
    "conda_env_observed": "neurolib"
  },
  "locks_read_not_written": [
    "S4_sbi/configs/notebook_39_41_closure/scientific_protocol_lock.json",
    "S4_sbi/configs/notebook_39_41_closure/execution_manifest.json"
  ],
  "integrity_status": "INTEGRITY_OK"
}

artifacts hashed: 47

In [11]:

summary = nb41.run_notebook41_claude()
show(summary)
print()
print((PROJECT_ROOT / summary["report"]).read_text(encoding="utf-8"))

{
  "created_utc": "2026-08-09T15:37:47.002954+00:00",
  "notebook": "claude_41",
  "final_part_ii_status": "RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY",
  "shipped_status": "HELDOUT_DESCRIPTIVE_EVIDENCE_ONLY",
  "invariant_across_admissible_readings": true,
  "intervention_status": "CONTROL_NOT_JUSTIFIED",
  "integrity_status": "INTEGRITY_OK",
  "dissertation_evidence_closure": "COMPLETE_AT_NOTEBOOK_41",
  "report": "S4_sbi/results/figure10_8d_7d/artifacts/notebook_41_claude/notebook_39_41_claude_unified_report.md",
  "simulations_run": 0
}

# Notebooks 39–41 (Claude) — Unified Closure Report

**Environment:** `neurolib` only · **Closure:** `COMPLETE_AT_NOTEBOOK_41` (no Notebook 42)
**Sealed:** unopened, no case arrays present

## Terminal status

| Field | Value |
|---|---|
| `global_uncertainty_status` | `NO_GO` (immutable from NB38) |
| `predictive_twin_status` | `PREDICTIVE_UNQUALIFIED` |
| 7D descriptive direction | `INDISTINGUISHABLE` |
| 8D descriptive direction | `INDISTINGUISHABLE` (non-deciding) |
| `sensitivity_concordance` | `CONCORDANT` |
| `intervention_status` | `CONTROL_NOT_JUSTIFIED` |
| **`final_part_ii_status`** | **`RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY`** |
| Invariant across admissible readings | `True` |

## Notebook 39 — admissibility

- Admissible families: `so_waveform`
- Excluded: `spindle_density` — `NON_DISCRIMINATIVE_EXCLUDED`
- Rate precision: `UNDERPOWERED_AT_FROZEN_BUDGET`
- Support conflict: Cursor `sample_set_difference` → Claude `definition_mismatch`
- Simulations: **0**

## Notebook 40 — re-measurement

- Reproduction of the Cursor sprint's published numbers: **136/136** → `REPRODUCED`
- Simulations charged to this audit: **16** (960 s simulated), plus 16 Cursor traces reused at zero cost — against the Cursor sprint's 68 runs / 6120 s
- 7D direction `INDISTINGUISHABLE`, vs V3 `UNFAVORABLE`
- 8D direction `INDISTINGUISHABLE`, vs V3 `INDISTINGUISHABLE`

## Notebook 41 — decision sensitivity

| Reading | Families counted | 7D direction | Terminal status | Admissible |
|---|---|---|---|---|
| `as_shipped_cursor` | so_waveform, spindle_density | MIXED | `HELDOUT_DESCRIPTIVE_EVIDENCE_ONLY` | no |
| `excluded_degenerate_point_estimate` | so_waveform | UNFAVORABLE | `RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY` | yes |
| `excluded_degenerate_sign_test_vs_v7` | so_waveform | INDISTINGUISHABLE | `RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY` | yes |
| `excluded_degenerate_sign_test_vs_v3` | so_waveform | UNFAVORABLE | `RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY` | yes |
| `no_admissible_direction` | — | UNINTERPRETABLE | `RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY` | yes |

Admissible readings agree on `RELIABILITY_DIAGNOSTIC_FRAMEWORK_ONLY`. No choice of alpha produces the shipped status on the admissible evidence. A significant favorable reading would need 13 of 16 candidates to beat V7; the observed count is 4.

## Intervention

`CONTROL_NOT_JUSTIFIED` — all four preregistration elements searched by name
across 6 locks and preregistrations; none present.
Intervention simulations run: **0**.

## Dissertation paragraph

> Global posterior qualification failed on both tracks and the failure was not repaired downstream. Of the two objective-disjoint physiology families, only slow-oscillation waveform morphology has a decision rule capable of returning an unfavorable answer within the range this model can produce; the spindle-density rule admits every attainable density and was excluded before its results were read. On that single admissible family the posterior candidates could not be distinguished from the frozen V7 point estimate on the primary track (4/16 candidates better, sign-test p = 0.077) or on the sensitivity track (p = 1.000), and were significantly worse than the older V3 estimate on the primary track (2/16, p = 0.0042). Repeated simulation confirms the spread across candidates is a property of the parameter draw rather than simulator noise (93% of the variance on the primary track), so the width of that spread is itself a posterior finding. All 34 simulated arms -- every posterior candidate and both differential-evolution baselines -- produced no detector-visible sigma events, which is a limitation of the thalamo-cortical configuration rather than a comparison among arms. No preregistered intervention exists in the record, so no control experiment could be launched, and Part II closes as a reliability diagnostic framework rather than as validated posterior inference.

### Retracted

> The candidate simulations retained limited held-out physiological consistency relative to a frozen DE baseline on objective-disjoint descriptive metrics, but neither calibrated posterior uncertainty nor reliable intervention prediction was established.

The clause 'retained limited held-out physiological consistency relative to a frozen DE baseline' rests on the spindle-density FAVORABLE label. That label is a tie between two arms that both produced zero events, under a rule that admits every density the model can generate. On the one family with discriminative power the candidates are indistinguishable from V7 on both tracks and significantly worse than V3 on the primary track.

## Audits

- Sealed entries: `sealed_state_registry.json` · case arrays: `none`
- Notebook 42: `absent`
- Files written, all under the three Claude roots: 47
- `integrity_status`: **`INTEGRITY_OK`**

## Post-hoc disclosure

This plan was written after reading the executed Cursor 39-41 outputs. Every threshold below was chosen with those outputs visible and is disclosed as post-hoc. The closure conclusion is carried by agreement across all admissible readings (see notebook 41 decision sensitivity), not by any one of these numbers.


## Closure

`dissertation_evidence_closure = COMPLETE_AT_NOTEBOOK_41`. There is no Notebook 42, the
sealed bank was never opened, and `global_uncertainty_status` remains `NO_GO`.